export const BONGAIGAON_DIRECTORY_SEED = [
  // ─── Healthcare & Hospitals ───────────────────────────────────────────────
  {
    id: 'bg-swagat-hospital',
    name: 'Swagat Hospital & Research Centre',
    category: 'healthcare',
    description: 'Multi-specialty hospital providing 24/7 emergency care, ICU, cardiology, advanced general surgery, orthopedic care, and fertility clinic.',
    address: 'Near BOC Gate, Chapaguri Road, Bongaigaon',
    city: 'Bongaigaon',
    latitude: 26.4682,
    longitude: 90.5485,
    phone: '+91 3664 230055',
    website: 'https://swagathospitalbongaigaon.in',
    imageUrl: 'https://images.unsplash.com/photo-1519494026892-80bbd2d6fd0d?w=800&auto=format&fit=crop&q=80',
    rating: 4.5,
    reviewCount: 120,
    isVerified: true,
    isSponsored: true,
    openingHours: 'Open 24 Hours (Emergency)',
    isClaimed: false,
    claimStatus: 'unclaimed',
  },
  {
    id: 'bg-lahrc-hospital',
    name: 'Lower Assam Hospital & Research Centre (LAHRC)',
    category: 'healthcare',
    description: 'Super-specialized hospital in North Bongaigaon offering comprehensive medical diagnostics, 24/7 trauma emergency, advanced surgery, and specialized ICU.',
    address: 'North Bongaigaon, Near Railway Overbridge, Bongaigaon',
    city: 'Bongaigaon',
    latitude: 26.4756,
    longitude: 90.5512,
    phone: '+91 3664 233366',
    website: 'https://lahrc.in',
    imageUrl: 'https://images.unsplash.com/photo-1586773860418-d37222d8fce3?w=800&auto=format&fit=crop&q=80',
    rating: 4.4,
    reviewCount: 180,
    isVerified: true,
    isSponsored: false,
    openingHours: 'Open 24 Hours',
    isClaimed: false,
    claimStatus: 'unclaimed',
  },
  {
    id: 'bg-civil-hospital',
    name: 'Bongaigaon Civil Hospital',
    category: 'healthcare',
    description: 'Primary government healthcare hospital in the district providing maternal and child care, generic pharmacy, casualty ward, and outpatient consultations.',
    address: 'Hatimutra, Bongaigaon',
    city: 'Bongaigaon',
    latitude: 26.4612,
    longitude: 90.563,
    phone: '+91 3664 222144',
    imageUrl: 'https://images.unsplash.com/photo-1516549655169-df83a0774514?w=800&auto=format&fit=crop&q=80',
    rating: 4.1,
    reviewCount: 95,
    isVerified: true,
    isSponsored: false,
    openingHours: 'Open 24 Hours',
    isClaimed: false,
    claimStatus: 'unclaimed',
  },

  // ─── Hotels & Stays ───────────────────────────────────────────────────────
  {
    id: 'bg-cygnett-park-meghna',
    name: 'Cygnett Park Meghna',
    category: 'hotels',
    description: 'Premier 4-star business and leisure hotel on Chapaguri Road featuring luxury executive suites, fine-dining restaurant, conference halls, and banquet facilities.',
    address: 'Chapaguri Road, Near Meghna Hyundai, Bongaigaon',
    city: 'Bongaigaon',
    latitude: 26.4795,
    longitude: 90.5452,
    phone: '+91 3664 241000',
    website: 'https://www.cygnetthotels.com',
    imageUrl: 'https://images.unsplash.com/photo-1566073771259-6a8506099945?w=800&auto=format&fit=crop&q=80',
    rating: 4.6,
    reviewCount: 340,
    isVerified: true,
    isSponsored: true,
    openingHours: '24/7 Front Desk',
    isClaimed: false,
    claimStatus: 'unclaimed',
  },
  {
    id: 'bg-hotel-himalaya',
    name: 'Hotel Himalaya',
    category: 'hotels',
    description: 'Established hospitality destination in Bongaigaon near BOC Gate offering well-appointed family rooms, multi-cuisine dining, and celebration hall.',
    address: 'Chapaguri Road, BOC Gate, Bongaigaon',
    city: 'Bongaigaon',
    latitude: 26.4705,
    longitude: 90.549,
    phone: '+91 3664 231122',
    imageUrl: 'https://images.unsplash.com/photo-1590490360182-c33d57733427?w=800&auto=format&fit=crop&q=80',
    rating: 4.2,
    reviewCount: 160,
    isVerified: true,
    isSponsored: false,
    openingHours: '24/7 Front Desk',
    isClaimed: false,
    claimStatus: 'unclaimed',
  },
  {
    id: 'bg-hotel-raj-palace',
    name: 'Hotel Raj Palace',
    category: 'hotels',
    description: 'Comfortable transit lodging near Station Road and Mayapuri, popular among business travelers and tourists visiting the district.',
    address: 'Station Road, Mayapuri, Bongaigaon',
    city: 'Bongaigaon',
    latitude: 26.4635,
    longitude: 90.554,
    phone: '+91 94350 22334',
    imageUrl: 'https://images.unsplash.com/photo-1582719508461-905c673771fd?w=800&auto=format&fit=crop&q=80',
    rating: 4.0,
    reviewCount: 88,
    isVerified: true,
    isSponsored: false,
    openingHours: '24/7 Front Desk',
    isClaimed: false,
    claimStatus: 'unclaimed',
  },

  // ─── Open Markets & Bazaars ───────────────────────────────────────────────
  {
    id: 'bg-shohid-bedi-bazar',
    name: 'Shohid Bedi Sabji Bazar',
    category: 'markets',
    description: 'Primary daily open-air vegetable and farmers market in Borpara featuring direct-from-farm fresh greens, native river fish, herbs, and seasonal fruits.',
    address: 'Shohid Bedi, Borpara, Bongaigaon',
    city: 'Bongaigaon',
    latitude: 26.464,
    longitude: 90.558,
    imageUrl: 'https://images.unsplash.com/photo-1488459716781-31db52582fe9?w=800&auto=format&fit=crop&q=80',
    rating: 4.5,
    reviewCount: 210,
    isVerified: true,
    isSponsored: false,
    openingHours: '6:00 AM - 12:30 PM Daily',
    isClaimed: false,
    claimStatus: 'unclaimed',
  },
  {
    id: 'bg-chapaguri-bazaar',
    name: 'Chapaguri Daily Bazaar',
    category: 'markets',
    description: 'Bustling commercial market near Chapaguri Junction along NH-27 offering fresh farm harvest, traditional bamboo goods, dairy, and spices.',
    address: 'Chapaguri Junction, NH-27, Bongaigaon',
    city: 'Bongaigaon',
    latitude: 26.482,
    longitude: 90.544,
    imageUrl: 'https://images.unsplash.com/photo-1533900298318-6b8da08a523e?w=800&auto=format&fit=crop&q=80',
    rating: 4.3,
    reviewCount: 130,
    isVerified: true,
    isSponsored: false,
    openingHours: '7:00 AM - 8:30 PM Daily',
    isClaimed: false,
    claimStatus: 'unclaimed',
  },
  {
    id: 'bg-new-bongaigaon-china-market',
    name: 'New Bongaigaon China Market',
    category: 'markets',
    description: 'Historic vibrant retail bazaar in Railway Colony famous for footwear, casual apparel, electronics, accessories, and local tea stalls.',
    address: 'Railway Colony, New Bongaigaon',
    city: 'Bongaigaon',
    latitude: 26.488,
    longitude: 90.528,
    imageUrl: 'https://images.unsplash.com/photo-1555396273-367ea4eb4db5?w=800&auto=format&fit=crop&q=80',
    rating: 4.4,
    reviewCount: 310,
    isVerified: true,
    isSponsored: false,
    openingHours: '9:30 AM - 8:00 PM Daily',
    isClaimed: false,
    claimStatus: 'unclaimed',
  },

  // ─── Retail & Modern Stores ───────────────────────────────────────────────
  {
    id: 'bg-reliance-smart-bazaar',
    name: 'Reliance SMART Bazaar',
    category: 'shops',
    description: 'Large departmental hypermarket on Salmara Road featuring fresh packaged groceries, dairy, kitchenware, household essentials, and affordable fashion.',
    address: 'Ward No. 13, Salmara Road, Chapaguri North, Bongaigaon',
    city: 'Bongaigaon',
    latitude: 26.4835,
    longitude: 90.546,
    phone: '1800 891 0001',
    imageUrl: 'https://images.unsplash.com/photo-1578916171728-46686eac8d58?w=800&auto=format&fit=crop&q=80',
    rating: 4.5,
    reviewCount: 450,
    isVerified: true,
    isSponsored: true,
    openingHours: '8:00 AM - 10:00 PM',
    isClaimed: false,
    claimStatus: 'unclaimed',
  },
  {
    id: 'bg-vishal-mega-mart',
    name: 'Vishal Mega Mart',
    category: 'shops',
    description: 'Multi-floor family shopping destination near BOC Gate providing value-for-money fashion apparel, home decor, cookware, and packaged food.',
    address: 'Near BOC Gate, Chapaguri Road, Bongaigaon',
    city: 'Bongaigaon',
    latitude: 26.469,
    longitude: 90.548,
    imageUrl: 'https://images.unsplash.com/photo-1441986300917-64674bd600d8?w=800&auto=format&fit=crop&q=80',
    rating: 4.3,
    reviewCount: 290,
    isVerified: true,
    isSponsored: false,
    openingHours: '9:30 AM - 9:30 PM',
    isClaimed: false,
    claimStatus: 'unclaimed',
  },
  {
    id: 'bg-reliance-digital',
    name: 'Reliance Digital',
    category: 'shops',
    description: 'Specialty consumer electronics showroom carrying smartphones, laptops, smart TVs, sound systems, refrigeration, and authorized warranty service.',
    address: 'Chapaguri Road, Bongaigaon',
    city: 'Bongaigaon',
    latitude: 26.4715,
    longitude: 90.5475,
    imageUrl: 'https://images.unsplash.com/photo-1550009158-9ebf69173e03?w=800&auto=format&fit=crop&q=80',
    rating: 4.4,
    reviewCount: 175,
    isVerified: true,
    isSponsored: false,
    openingHours: '10:00 AM - 9:00 PM',
    isClaimed: false,
    claimStatus: 'unclaimed',
  },
  {
    id: 'bg-jack-n-jill-mall',
    name: 'Jack \'n Jill Shopping Mall',
    category: 'shops',
    description: 'Modern retail fashion center on Chapaguri Road offering kids wear, casual youth apparel, formal menswear, and personal accessories.',
    address: 'Opposite Mahindra Tractor, Chapaguri Road, Bongaigaon',
    city: 'Bongaigaon',
    latitude: 26.474,
    longitude: 90.5465,
    imageUrl: 'https://images.unsplash.com/photo-1481437156560-3205f6a55735?w=800&auto=format&fit=crop&q=80',
    rating: 4.2,
    reviewCount: 115,
    isVerified: true,
    isSponsored: false,
    openingHours: '10:00 AM - 9:00 PM',
    isClaimed: false,
    claimStatus: 'unclaimed',
  },

  // ─── Local Stores & Provisions ────────────────────────────────────────────
  {
    id: 'bg-bongaigaon-mart',
    name: 'Bongaigaon Mart & General Store',
    category: 'local_stores',
    description: 'Neighborhood grocery and daily provisions store in Borpara offering pantry staples, packaged dairy, personal care goods, and bakery products.',
    address: 'Main Road, Borpara, Bongaigaon',
    city: 'Bongaigaon',
    latitude: 26.4655,
    longitude: 90.5565,
    imageUrl: 'https://images.unsplash.com/photo-1604719312566-8912e9227c6a?w=800&auto=format&fit=crop&q=80',
    rating: 4.4,
    reviewCount: 80,
    isVerified: true,
    isSponsored: false,
    openingHours: '8:00 AM - 9:30 PM',
    isClaimed: false,
    claimStatus: 'unclaimed',
  },
  {
    id: 'bg-vivid-mart',
    name: 'Vivid Mart',
    category: 'local_stores',
    description: 'Neighborhood convenience store for packaged foods, cold drinks, household supplies, and quick doorstep provisions for nearby colonies.',
    address: 'Main Road, Near Mayapuri, Borpara, Bongaigaon',
    city: 'Bongaigaon',
    latitude: 26.4648,
    longitude: 90.557,
    imageUrl: 'https://images.unsplash.com/photo-1526367790999-0150786686a2?w=800&auto=format&fit=crop&q=80',
    rating: 4.3,
    reviewCount: 65,
    isVerified: true,
    isSponsored: false,
    openingHours: '8:00 AM - 10:00 PM',
    isClaimed: false,
    claimStatus: 'unclaimed',
  },

  // ─── Institutions & Colleges ──────────────────────────────────────────────
  {
    id: 'bg-bongaigaon-college',
    name: 'Bongaigaon College',
    category: 'institutions',
    description: 'Premier higher educational institution founded in 1964 offering undergraduate arts and commerce education, digital archives, and student forums.',
    address: 'College Road, Bongaigaon',
    city: 'Bongaigaon',
    latitude: 26.462,
    longitude: 90.5605,
    phone: '+91 3664 222160',
    website: 'https://www.bongaigaoncollege.ac.in',
    imageUrl: 'https://images.unsplash.com/photo-1497366216548-37526070297c?w=800&auto=format&fit=crop&q=80',
    rating: 4.6,
    reviewCount: 380,
    isVerified: true,
    isSponsored: false,
    openingHours: '9:00 AM - 5:00 PM (Mon-Sat)',
    isClaimed: false,
    claimStatus: 'unclaimed',
  },
  {
    id: 'bg-birjhora-mahavidyalaya',
    name: 'Birjhora Mahavidyalaya',
    category: 'institutions',
    description: 'Top-ranked regional science college offering degree courses across physical and biological sciences, research seminars, and environmental initiatives.',
    address: 'Eco-Park Road, Bongaigaon',
    city: 'Bongaigaon',
    latitude: 26.467,
    longitude: 90.562,
    phone: '+91 3664 222150',
    website: 'https://www.birjhoramahavidyalaya.ac.in',
    imageUrl: 'https://images.unsplash.com/photo-1562774053-701939374585?w=800&auto=format&fit=crop&q=80',
    rating: 4.7,
    reviewCount: 410,
    isVerified: true,
    isSponsored: false,
    openingHours: '9:00 AM - 5:00 PM (Mon-Sat)',
    isClaimed: false,
    claimStatus: 'unclaimed',
  },
  {
    id: 'bg-bongaigaon-polytechnic',
    name: 'Bongaigaon Polytechnic',
    category: 'institutions',
    description: 'State government technical diploma institute providing practical engineering workshops, technical certifications, and skill development.',
    address: 'Dhaligaon Road, Bongaigaon',
    city: 'Bongaigaon',
    latitude: 26.495,
    longitude: 90.512,
    phone: '+91 3664 233180',
    imageUrl: 'https://images.unsplash.com/photo-1581092160607-ee22621dd758?w=800&auto=format&fit=crop&q=80',
    rating: 4.5,
    reviewCount: 190,
    isVerified: true,
    isSponsored: false,
    openingHours: '9:30 AM - 4:30 PM (Mon-Fri)',
    isClaimed: false,
    claimStatus: 'unclaimed',
  },
  {
    id: 'bg-bongaigaon-law-college',
    name: 'Bongaigaon Law College',
    category: 'institutions',
    description: 'Established center for legal education offering LLB programs, moot court competitions, legal aid clinics, and citizen advocacy workshops.',
    address: 'Borpara, Bongaigaon',
    city: 'Bongaigaon',
    latitude: 26.463,
    longitude: 90.559,
    phone: '+91 3664 223500',
    website: 'https://bongaigaonlawcollege.com',
    imageUrl: 'https://images.unsplash.com/photo-1453728013993-6d66e9c9123a?w=800&auto=format&fit=crop&q=80',
    rating: 4.4,
    reviewCount: 110,
    isVerified: true,
    isSponsored: false,
    openingHours: '9:30 AM - 4:30 PM (Mon-Sat)',
    isClaimed: false,
    claimStatus: 'unclaimed',
  },
];
